---
- name: Testing andrewrothstein.task
  hosts: all
  tasks:
    - name: Installing andrewrothstein.task
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'task --version'
      ansible.builtin.command: /usr/local/bin/task --version
      changed_when: false
      register: task_test_output
    - name: Output of 'task --version'
      ansible.builtin.debug:
        msg: '{{ task_test_output.stdout }}'
