---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/task --version
    register: task_test_output
  - name: task --version
    debug:
      msg: '{{ task_test_output.stdout }}'
