---
- include_role:
    name: andrewrothstein.unarchive-deps
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: look for install in {{ task_exe }}
  become: true
  stat:
    path: '{{ task_exe }}'
  changed_when: false
  register: task_binary
- when: not task_binary.stat.exists
  block:
    - name: downloading {{ task_url }} to {{ task_tmp_tgz }}
      become: true
      become_user: root
      get_url:
        url: '{{ task_url }}'
        dest: '{{ task_tmp_tgz }}'
        mode: 0644
        checksum: '{{ task_checksum }}'
    - name: mkdir -p {{ task_install_dir }}
      become: true
      become_user: root
      file:
        path: '{{ task_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchive {{ task_tmp_tgz }} to {{ task_install_dir }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ task_tmp_tgz }}'
        dest: '{{ task_install_dir }}'
        creates: '{{ task_exe }}'
  always:
    - name: rm -f {{ task_tmp_tgz }}
      become: true
      become_user: root
      file:
        path: '{{ task_tmp_tgz }}'
        state: absent
- name: linking {{ task_link }} to {{ task_exe }}
  become: true
  become_user: root
  file:
    src: '{{ task_exe }}'
    dest: '{{ task_link }}'
    state: link
