---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Look for install in {{ task_exe }}
  become: true
  ansible.builtin.stat:
    path: '{{ task_exe }}'
  changed_when: false
  register: task_binary
- name: Downloading and installing task
  when: not task_binary.stat.exists
  block:
    - name: Downloading {{ task_url }} to {{ task_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ task_url }}'
        dest: '{{ task_tmp_tgz }}'
        mode: '644'
        checksum: '{{ task_checksum }}'
    - name: Mkdir -p {{ task_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ task_install_dir }}'
        state: directory
        mode: '755'
    - name: Unarchive {{ task_tmp_tgz }} to {{ task_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ task_tmp_tgz }}'
        dest: '{{ task_install_dir }}'
        creates: '{{ task_exe }}'
  always:
    - name: Rm -f {{ task_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ task_tmp_tgz }}'
        state: absent
- name: Linking {{ task_link }} to {{ task_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ task_exe }}'
    dest: '{{ task_link }}'
    state: link
